// <auto-generated />
namespace BibliotheekBeheerModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ffff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ffff));
        
        string IMigrationMetadata.Id
        {
            get { return "202304120851175_ffff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
